JNI方法注册分为静态注册和动态注册，其中静态注册多用于NDK开发，而动态注册多用于Framework开发。

一.静态实现方法
1.先实现一个JAVA类
在这里实现一个HellJNI类加载一个hello的JNI接口
-------------------------------------------------------------
public class HelloJNI {
   static {
      System.loadLibrary("hello"); // Load native library at runtime
                                   // hello.dll (Windows) or libhello.so (Unixes)
   }

   // Declare a native method sayHello() that receives nothing and returns void
   private native void sayHello();

   // Test Driver
   public static void main(String[] args) {
      new HelloJNI().sayHello();  // invoke the native method
   }
}
-------------------------------------------------------------

2.我们使用JAVA来编译出.class文件
 javac HelloJNI.java

3.生成C/C++文件
 javah HelloJNI

HelloJNI.h文件
-------------------------------------------------------------
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HelloJNI */

#ifndef _Included_HelloJNI
#define _Included_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_HelloJNI_sayHello(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
-------------------------------------------------------------
1. JNIEnv *：这是一个指向JNI运行环境的指针，后面我们会看到，我们通过这个指针访问JNI函数
2. jobject：这里指代java中的this对象
-------------------------------------------------------------

二.动态注册实现方法
JNI中有一种结构用来记录Java的Native方法和JNI方法的关联关系，它就是JNINativeMethod
-------------------------------------------------------------
创建：
static const JNINativeMethod gMethods[] = {
    {"setCamera",            "(Landroid/hardware/Camera;)V",    (void *)android_media_MediaRecorder_setCamera},
    {"setVideoSource",       "(I)V",                            (void *)android_media_MediaRecorder_setVideoSource}
}
-------------------------------------------------------------
上面定义了一个JNINativeMethod类型的gMethods数组，里面存储的就是MediaRecorder的Native方法与JNI层方法的对应关系，
其中注释1处”setCamera”是Java层的Native方法，它对应的JNI层的方法为android_media_MediaRecorder_setCamera。
”()V”是start方法的签名信息
只定义JNINativeMethod 类型的数组是没有用的，还需要注册它，注册的方法为register_android_media_MediaRecorder
注册:
-------------------------------------------------------------
int register_android_media_MediaRecorder(JNIEnv *env)
{
    return AndroidRuntime::registerNativeMethods(env,
                "android/media/MediaRecorder", gMethods, NELEM(gMethods));
}
-------------------------------------------------------------
先写到这
2023-9-18
